In [2]:
import numpy as np

# Array using NumPy

In [4]:
arr = np.array(  [ [2, 2, 3],
                   [4, 2, 5] ]  )

print(arr)

[[2 2 3]
 [4 2 5]]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


In [8]:
#Creating array using passsed list
a = np.array(  [ [1, 2, 3],
                 [4, 5, 6]  ], dtype='float'  )   

#creating array using passed tuple
b = np.array((1, 3, 2))

print(a)
print("datatype of a:", a.dtype)
print(b)
print("datatypr of b:", b.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
datatype of a: float64
[1 3 2]
datatypr of b: int64


In [9]:
c = np.zeros((3,4))
print(c)

#a 3*3 matrix with all the values equal to 6
d = np.full((3,3), 6, dtype = 'complex')
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


### Array Creation Techniques

In [ ]:
A = np.ones((3,2))
print(A)

B = np.random.random((3,2))
print(B)

#Sequential array with steps of 5
f = np.arange(0, 30, 5)
print(f)
#Sequential array with 10 values between 0 and 5
g = np.linspace(0, 5, 10)   #linearSpace
print(g)

### Array Manipulation

In [15]:
#Reshaping a 3*4 array to 2*2*3
arr1 = np.array([[1, 2, 3, 4], 
                [5, 2, 4, 2], 
                [1, 2, 0, 1]]) 
  
newarr = arr1.reshape(2, 2, 3) 
print(newarr)

[[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [16]:
#Flatten the array
flarr = arr1.flatten()
print(flarr)

[1 2 3 4 5 2 4 2 1 2 0 1]


# Array Indexing

In [17]:
arr2 = np.array([[-1, 2, 0, 4], 
                [4, -0.5, 6, 0], 
                [2.6, 0, 7, 8], 
                [3, -7, 4, 2.0]]) 

In [25]:
#Slicing Array
temp = arr2[:2, ::2] 
 
##    arr[ <indexForStartingRow>  :  <indexForEndRow+1>  :  <inStepsOf>,
##        <indexForStartingColumn>  :  <indexForEndColumn+1>  :  <inStepsOf>]

print(temp)

[[-1.  0.]
 [ 4.  6.]]


In [26]:
# Integer array indexing 
temp1 = arr2[[0, 1, 2, 3], [3, 2, 1, 0]] 
print ("\nElements at indices (0, 3), (1, 2), (2, 1), (3, 0):\n", temp1)


Elements at indices (0, 3), (1, 2), (2, 1), (3, 0):
 [4. 6. 0. 3.]


In [27]:
# boolean array indexing
cond = arr2 > 0 # cond is a boolean array 
temp = arr2[cond] 
print ("\nElements greater than 0:\n", temp) 


Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


# Basic Operations 

### Operations on single array

In [29]:
arr3 = np.array(  [ [1, 5, 3],
                    [8, 6, 4]  ] )

# add 1 to every element 
print ("Adding 1 to every element:", arr3 + 1) 

# subtract 3 from each element 
print ("Subtracting 3 from each element:", arr3 - 3) 
  
# multiply each element by 10 
print ("Multiplying each element by 10:", arr3 * 10) 
  
# square each element 
print ("Squaring each element:", arr3**2) 

Adding 1 to every element: [[2 6 4]
 [9 7 5]]
Subtracting 3 from each element: [[-2  2  0]
 [ 5  3  1]]
Multiplying each element by 10: [[10 50 30]
 [80 60 40]]
Squaring each element: [[ 1 25  9]
 [64 36 16]]


In [30]:
# modify existing array 
arr3 *= 2
print ("Doubled each element of original array:", arr3) 

Doubled each element of original array: [[ 2 10  6]
 [16 12  8]]


In [31]:
# transpose of array 
arr3 = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]]) 
  
print ("\nOriginal array:\n", arr3) 
print ("Transpose of array:\n", arr3.T) 


Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


### Unary operators

In [32]:
arr4 = np.array([[1, 5, 6], 
                [4, 7, 2], 
                [3, 1, 9]]) 
  
# maximum element of array 
print ("Largest element is:", arr4.max()) 
print ("Row-wise maximum elements:", 
                    arr4.max(axis = 1)) 
  
# minimum element of array 
print ("Largest element is:", arr4.max()) 
print ("Column-wise minimum elements:", 
                        arr4.min(axis = 0)) 

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Largest element is: 9
Column-wise minimum elements: [1 1 2]


In [39]:
# sum of array elements 
print ("Sum of all array elements:", 
                            arr4.sum()) 
print ("Sum of all array elements:", 
                            arr4.sum(axis = 0)) 
print ("Sum of all array elements:", 
                            arr4.sum(axis = 1)) 
  
# cumulative sum along each row 
print ("\nCumulative sum along each row:\n", 
                        arr4.cumsum(axis = 1)) 
# cumulative sum along each column 
print ("\nCumulative sum along each row:\n", 
                        arr4.cumsum(axis = 0)) 

Sum of all array elements: 38
Sum of all array elements: [ 8 13 17]
Sum of all array elements: [12 13 13]

Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]

Cumulative sum along each row:
 [[ 1  5  6]
 [ 5 12  8]
 [ 8 13 17]]


### Binary operators

In [63]:
a = np.array([[1, 2], 
            [3, 4]]) 
b = np.array([[4, 3], 
            [2, 1]]) 
  
# add arrays 
print ("Array sum:\n", a + b) 
  
# multiply arrays (elementwise multiplication) 
print ("Array (Element Wise) multiplication:\n", a*b) 
  
# matrix multiplication 
print ("Matrix multiplication:\n", a.dot(b)) 

Array sum:
 [[5 5]
 [5 5]]
Array (Element Wise) multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


### Universal functions (ufunc):
NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.

In [74]:
a = np.array([0, np.pi/2, np.pi])
print(a)
print ("\nSine values of array elements:", np.sin(a)) 

[0.         1.57079633 3.14159265]

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [75]:
a = np.array([0, 1, 2, 3]) 
print ("Exponent of array elements:", np.exp(a)) 
  
# square root of array values 
print ("Square root of array elements:", np.sqrt(a)) 

Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


### Sorting array: 
There is a simple np.sort method for sorting NumPy arrays.

In [78]:
a = np.array([[1, 4, 2], 
                 [3, 4, 6], 
              [0, -1, 5]]) 
  
# sorted array 
print ("Array elements in sorted order:\n", 
                    np.sort(a, axis = None)) 

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]


In [79]:
# sort array row-wise 
print ("Row-wise sorted array:\n", 
                np.sort(a, axis = 1)) 
  
# specify sort algorithm 
print ("Column wise sort by applying merge-sort:\n", 
            np.sort(a, axis = 0, kind = 'mergesort')) 

Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [80]:
# Example to show sorting of structured array 
# set alias names for dtypes 
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)] 
  
# Values to be put in array 
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),  
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)] 
             
# Creating array 
arr = np.array(values, dtype = dtypes) 
print ("\nArray sorted by names:\n", 
            np.sort(arr, order = 'name')) 
              
print ("Array sorted by grauation year and then cgpa:\n", 
                np.sort(arr, order = ['grad_year', 'cgpa'])) 


Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by grauation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


In [82]:
print(arr.dtype)

[('name', 'S10'), ('grad_year', '<i8'), ('cgpa', '<f8')]


# ndarray

### Numpy numpy.ndarray.\_\_ge\_\_() or \_\_gt\_\_()

In [83]:
# make an array with numpy 
gfg = np.array([1, 2, 3, 4, 5, 6]) 
  
# applying numpy.__ge__() method 
print(gfg.__ge__(4)) 

# make an array with numpy 
gfg1 = np.array([[1, 2, 3, 4, 5, 6], 
                [6, 5, 4, 3, 2, 1]]) 
  
# applying numpy.__ge__() method 
print(gfg1.__ge__(4)) 

[False False False  True  True  True]
[[False False False  True  True  True]
 [ True  True  True False False False]]


### Numpy numpy.ndarray.\_\_or\_\_() or \_\_and\_\_()

In [84]:
# make an array with numpy 
gfg = np.array([1, 2, 3, 4, 5]) 
     
# applying ndarray.__or__() method 
print(gfg.__or__(2)) 

# make an array with numpy 
gfg = np.array([[1, 2, 3, 4, 5], 
                [6, 5, 4, 3, 2]]) 
     
# applying ndarray.__or__() method 
print(gfg.__or__(1)) 

[3 2 3 6 7]
[[1 3 3 5 5]
 [7 5 5 3 3]]


### Numpy numpy.ndarray.\_\_le\_\_() or \_\_lt\_\_()
We can find that which element in an array is less then or equal to the value which is provided in the parameter. It will return you numpy array with boolean type having only values True and False.

In [85]:
# make an array with numpy 
gfg = np.array([1, 2, 3, 4, 5, 6]) 
  
# applying numpy.__le__() method 
print(gfg.__le__(4)) 

# make an array with numpy 
gfg = np.array([[1, 2, 3, 4, 5, 6], 
                [6, 5, 4, 3, 2, 1]]) 
  
# applying numpy.__le__() method 
print(gfg.__le__(4)) 

[ True  True  True  True False False]
[[ True  True  True  True False False]
 [False False  True  True  True  True]]


### Numpy numpy.ndarray.\_\_ne\_\_() or \_\_eq\_\_()

In [92]:
# make an array with numpy 
gfg = np.array([1, 2, 3, 4, 5, 6]) 
  
# applying numpy.__ne__() method 
print(gfg.__ne__(4)) 

# make an array with numpy 
gfg = np.array([[1, 2, 3, 4, 5, 6], 
                [6, 5, 4, 3, 2, 1]]) 
  
# applying numpy.__ne__() method 
print(gfg.__ne__(4)) 

[ True  True  True False  True  True]
[[ True  True  True False  True  True]
 [ True  True False  True  True  True]]


### Numpy numpy.ndarray.\_\_truediv\_\_() or \_\_mul\_\_() or \_\_imul\_\_() for all datatypes
we can divide a particular value that is provided as a parameter in the ndarray.__truediv__() method. Value will be divided to each and every element in a numpy array.

In [90]:
# make an array with numpy 
gfg = np.array([1, 2.5, 3, 4.8, 5]) 
   
# applying ndarray.__truediv__() method 
print(gfg.__truediv__(2)) 


# make an array with numpy 
gfg = np.array([[1, 2, 3, 4.45, 5], 
                [6, 5.5, 4, 3, 2.62]]) 
   
# applying ndarray.__truediv__() method 
print(gfg.__truediv__(3)) 

# applying ndarray.__mul__() method 
print(gfg.__mul__(5)) 

[0.5  1.25 1.5  2.4  2.5 ]
[[0.33333333 0.66666667 1.         1.48333333 1.66666667]
 [2.         1.83333333 1.33333333 1.         0.87333333]]
[[ 5.   10.   15.   22.25 25.  ]
 [30.   27.5  20.   15.   13.1 ]]


### Numpy numpy.ndarray.\_\_floordiv\_\_()
divides and returns the floor value

In [99]:
# make an array with numpy 
gfg = np.array([1, 2.5, 3, 4.8, 5]) 
   
# applying ndarray.__floordiv__() method 
print(gfg.__floordiv__(2)) 

# make an array with numpy 
gfg = np.array([[1, 2, 3, 4.45, 5], 
                [6, 5.5, 4, 3, 2.62]]) 
   
# applying ndarray.__floordiv__() method 
print(gfg.__floordiv__(3)) 

[0. 1. 1. 2. 2.]
[[0. 0. 1. 1. 1.]
 [2. 1. 1. 1. 0.]]


### Numpy numpy.ndarray.\_\_sub\_\_() or \_\_add\_\_()

In [91]:
gfg = np.array([1, 2, 3, 4, 5]) 
   
# applying ndarray.__sub__() method 
print(gfg.__sub__(5)) 

# applying ndarray.__add__() method 
print(gfg.__add__(3)) 


[-4 -3 -2 -1  0]
[4 5 6 7 8]


### Numpy numpy.ndarray.\_\_mod\_\_()
Modulo

In [100]:
# make an array with numpy 
gfg = np.array([1, 2.5, 3, 4.8, 5]) 
    
# applying ndarray.__mod__() method 
print(gfg.__mod__(2)) 

# make an array with numpy 
gfg = np.array([[1, 2, 3, 4.45, 5], 
                [6, 5.5, 4, 3, 2.62]]) 
    
# applying ndarray.__mod__() method 
print(gfg.__mod__(3)) 

[1.  0.5 1.  0.8 1. ]
[[1.   2.   0.   1.45 2.  ]
 [0.   2.5  1.   0.   2.62]]


### Numpy numpy.ndarray.\_\_divmod\_\_()
In this example we can see that by using ndarray.__divmod__() method we get two arrays. One is with divided with value that is passed as parameter and other with mod values.

In [102]:
# make an array with numpy 
gfg = np.array([1, 2, 3, 4, 5]) 
    
# applying ndarray.__divmod__() method 
print(gfg.__divmod__(3)) 

# make an array with numpy 
gfg = np.array([[1, 2, 3, 4, 5], 
                [6, 5, 4, 3, 2]]) 
    
# applying ndarray.__divmod__() method 
print(gfg.__divmod__(3)) 

(array([0, 0, 1, 1, 1]), array([1, 2, 0, 1, 2]))
(array([[0, 0, 1, 1, 1],
       [2, 1, 1, 1, 0]]), array([[1, 2, 0, 1, 2],
       [0, 2, 1, 0, 2]]))


### Numpy numpy.ndarray.\_\_neg\_\_()

In [93]:
# make an array with numpy 
gfg = np.array([1, -2, 3, 4, 5, 6]) 
  
# applying numpy.__neg__() method 
print(gfg.__neg__()) 

# make an array with numpy 
gfg = np.array([[1, 2, -3, 4, 5, 6], 
                [-6, 5, 4, 3, 2, -1]]) 
  
# applying numpy.__neg__() method 
print(gfg.__neg__()) 

[-1  2 -3 -4 -5 -6]
[[-1 -2  3 -4 -5 -6]
 [ 6 -5 -4 -3 -2  1]]


In [95]:
#__lshift__() and __rshift__()

### Numpy numpy.ndarray.\_\_invert\_\_()

In [96]:
# make an array with numpy 
gfg = np.array([1, 2, 3, 4, 5]) 
    
# applying ndarray.__invert__() method 
print(gfg.__invert__()) 

# make an array with numpy 
gfg = np.array([[1, 2, 3, 4, 5], 
                [6, 5, 4, 3, 2]]) 
    
# applying ndarray.__invert__() method 
print(gfg.__invert__()) 

[-2 -3 -4 -5 -6]
[[-2 -3 -4 -5 -6]
 [-7 -6 -5 -4 -3]]


### Numpy numpy.ndarray.\_\_pow\_\_()


In [97]:
# make an array with numpy 
gfg = np.array([1, 2, 3, 4, 5]) 
     
# applying ndarray.__pow__() method 
print(gfg.__pow__(3)) 

# make an array with numpy 
gfg = np.array([[1, 2, 3, 4, 5], 
                [6, 5, 4, 3, 2]]) 
     
# applying ndarray.__pow__() method 
print(gfg.__pow__(2)) 

[  1   8  27  64 125]
[[ 1  4  9 16 25]
 [36 25 16  9  4]]
